### ISSUE TITLE
On the edge version, stylesheets are not found

### ISSUE THREAD

**Issue by thelastinuit** [pakyow/pakyow#105]
The stylesheets are missing... 

* Listening on tcp://0.0.0.0:3000                                                                                   [74/4669]
No view at path '/styles/pakyow-css/reset'
No view at path '/styles/pakyow-css/structure'
No view at path '/scripts/ring/pakyow'
No view at path '/styles/pakyow-css/theme'
No view at path '/styles/pakyow-css/syntax'
No view at path '/styles/pakyow-css/reset'
No view at path '/styles/pakyow-css/theme'
No view at path '/scripts/ring/pakyow'

However, they are located in public.

**Comment by bryanp** [comment]
Did you generate a brand new app from edge? If not, it's likely due to having just removed the code that injects default middleware into the app (including the `Static` file middleware). Take a look at the [generated app](https://github.com/pakyow/pakyow/tree/master/lib/generators/pakyow/app/templates) to see how you can resolve. Specifically the `middleware` block in `app/setup.rb` and the `middleware` folder.

**Comment by bryanp** [comment]
(sorry, submitted early and closed on accident)

Let me know if this works for you... if not I'll take a closer look.

**Comment by bryanp** [comment]
@thelastinuit Closing this; let me know if there's an ongoing issue.
