### ISSUE TITLE
Make current environment more consistent

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#128]
When starting the app in a non-development environment, it still appears to be started in development:

```
$ bundle exec pakyow s production
Puma 2.15.3 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://0.0.0.0:3000
```

This is because Pakyow doesn't change `RACK_ENV`, which Puma uses to determine the current environment. After some thought, I think the best solution would be for Pakyow's `server` and `console` commands to set `RACK_ENV` (if passed) and then run the app using the `RACK_ENV` value.

**Comment by karimmtarek** [comment]
@bryanp I'd like to pick this one up, any advise about where should I start?

**Comment by bryanp** [comment]
Take a look at the initializers in [console.rb](https://github.com/pakyow/pakyow/blob/master/lib/pakyow/commands/server.rb#L6) and [server.rb](https://github.com/pakyow/pakyow/blob/master/lib/pakyow/commands/console.rb#L8). One approach would be for the default value for the `environment` argument to be `ENV['RACK_ENV'] || :development`. Then, inside the initializer also set `ENV['RACK_ENV']` to the value. I believe that's the behavior we want here.

What do you think?

**Comment by karimmtarek** [comment]
@bryanp thanks for the advice.
I started (#143) by changing the environment argument default value to `ENV['RACK_ENV'] || :development` as you suggested, though I don't get this part:
> Then, inside the initializer also set ENV['RACK_ENV'] to the value.

If that's the case isn't it better to just remove `@environment` variable and replace it with `ENV['RAKE_ENV']`, so the initializer in console.rb would look like:
```
def initialize(environment: ENV['RACK_ENV'] || :development)
  ENV['RACK_ENV'] = environment
end
``` 
and then, call `ENV['RACK_ENV']` instead of  `@environment` in the `run` method, like:
```
def run
  load_app
  Pakyow::App.stage(ENV['RACK_ENV'])
  ...
end
```

And we do the same for the server.rb. Does that make any sense?

**Comment by bryanp** [comment]
Yep! That's exactly what I was trying to say 😬

**Comment by karimmtarek** [comment]
Perfect :+1: in this case what do you think of #143 ?
