### ISSUE TITLE
Reloader is not enabled in prototype environment

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#176]
The `reloader.enabled` config option should be `true` when starting up in the prototype environment. Currently, view changes aren't picked up without restarting the server.

**Comment by erlandsona** [comment]
I'm working on this now... where is the reloader.enabled config option supposed to be specified? I noticed that Pakyow wasn't "autoreloading" the code from the "Warmup" app. Is that on purpose / is this issue to address that particular functionality? Or is this specifically and only for views?

**Comment by jphager2** [comment]
Here is the [reloader config](https://github.com/pakyow/pakyow/blob/master/pakyow-core/lib/pakyow/core/config/reloader.rb).

**Comment by bryanp** [comment]
Where we define the reloaded config, we need to set the default option for `enabled` to `true` just like we do for development. 



On Fri, Jul 8, 2016 at 1:23 AM -0500, "John Hager" <notifications@github.com> wrote:












Here is the reloader config.

**Comment by erlandsona** [comment]
Maybe I'm totally mistaken but I've run throw this trying to figure out how to reproduce and it seems to me that given the current set of defaults this isn't actually an issue at all?

The only thing I don't think I understand about this issue is the meaning of "prototype". 

Currently since the default environment is development and the reloader config.opts.enabled is set to true for the development environment then the view reloading should be working by default. Or at least I observed as much.

So maybe I'm misunderstanding the meaning of prototype environment?
I could also be misunderstanding the point of the reloader... this isn't like a JS hot-module replacement thing where when you save a file it's automatically reloaded by the build tools and injected into the current markup right? To be clear it's supposed to behave within the request / response cycle more akin to like the Rails Autoloader right? EG: you don't have to restart the server on every change just refresh the page.

**Comment by jphager2** [comment]
@erlandsona, "prototype" is a defined environment (see one of it's config options [defined here](https://github.com/pakyow/pakyow/blob/2b5b0dbd754c2a0b28c0a1a59d1d476e9225e1d1/pakyow-core/lib/pakyow/core/config/app.rb)). To be honest, I can't find the documentation on this environment, but I remember reading/hearing something about it at some point. I'll keep looking.
