### ISSUE TITLE
Number of workers

### ISSUE THREAD

**Issue by waghanza** [pakyow/pakyow#491]
Hi @bryanp,

I can see in https://github.com/pakyow/pakyow/blob/bdbdf36b5b222c775449044d4e01810cd6cd0452/pakyow-core/lib/pakyow/config.rb#L66 that **5** workers are created in there is no `WORKERS` environment variable.

Why **5** ? Is there any recommended number ?

Regards,

**Comment by bryanp** [comment]
Generally speaking you should have one worker per core while leaving enough memory overhead. 5 workers was chosen as the default because it accommodates most Pakyow applications on a Heroku Dyno or similar. Heroku Dynos have 8 available cores, but we run up against the 512MB memory limit for all but the most trivial applications if we increase workers to 8.

This may change in v1.1 because of improved memory usage. Adding a worker in v1.1 only increases memory usage by < 50MB in most applications, so it may be possible to bump the default to 8. I'll need to do more testing to confirm though.

**Comment by waghanza** [comment]
I think :
+ a value could be recommended in `https://pakyow.com/docs/configuration`
+ the default value must be calculated

for example, in my use case, I actually use a 8 CPU / 16 G computer, but it could change (it will be a pain to change all implementations in https://github.com/the-benchmarker/web-frameworks :heart: )

**Comment by bryanp** [comment]
Agree on both points. Here's one approach to calculating a default value:

```ruby
require "etc"

Etc.nprocessors
```

It doesn't consider available memory, but I'm not sure we should since that can differ between applications.

**Comment by waghanza** [comment]
I think it could be calculated as-is, but also with a formula based on `number of memory ` **AND** `number of CPU`, as `puma` does to compute `WEB_CONCURRENCY`.

Seems, btw, to be quite a informal standard
https://devcenter.heroku.com/changelog-items/618

**Comment by bryanp** [comment]
Can you point me to where `puma` does this calculation?

**Comment by waghanza** [comment]
Sure, the `workers` number is computed in https://github.com/puma/puma/blob/a72c68b350e8c48b6c051ee729dd156c6044ca9d/lib/puma/configuration.rb#L187

**Comment by bryanp** [comment]
Sorry, maybe I misunderstood but I thought you were saying that puma computes workers based on memory / cpus?

**Comment by waghanza** [comment]
After re-read my thread, seems that I was saying that, ... but something else was in my mind :stuck_out_tongue:

**Comment by bryanp** [comment]
👍 no worries. I'm reluctant to compute concurrency based on available memory because of potential variability, but will keep this in mind. Thanks again for your input! Expect progress on this in the `v1.1` release.
