### ISSUE TITLE
Simplified bindings definition.

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#81]
Currently when defining bindings you have to do this:

``` ruby
Pakyow::App.bindings :post do
  scope :post do
    binding :title do; end
  end
end
```

I propose simplifying this to:

``` ruby
Pakyow::App.bindings :post do
  binding :title do; end
end
```

The assumed scope _and_ name of the binding set would be `post`. You could override the scope:

``` ruby
Pakyow::App.bindings :post, scope: :foo do
  binding :title do; end
end
```

**Comment by rjclardy** [comment]
+1

I think it would also be good to allow an array of scope names to be defined for a single binding set. Sometimes you can end up with pages that have two instances of the same scope. So if we had a page with two “user” scopes, one inside our nav element and the other inside the main content, we currently bind to the first one with `scope(:user)[0]` and the second with `scope(:user)[1]`. That works fine but it isn't obvious which scope is which. 

If we could configure the user bindings like so:
```
Pakyow::App.bindings :user, scope: [:user, :nav_user] do
   …
end
```
In our nav element we could set the scope like `data-scope=“nav_user”`. Then the other user scope could be defined normally like `data-scope=“user”`.

Then on the backend we could always access the nav user scope via `scope(:nav_user)` and the other user scope as `scope(:user)`, and they would both have the same set of bindings.

**Comment by bryanp** [comment]
Interesting, I like that!

**Comment by bryanp** [comment]
@rjclardy Instead of multiple scopes, what do you think about adding support for Binding mixins? Can't think of anything that multiple scopes would solve that mixins won't, and it follows the established pattern with routes.

**Comment by rjclardy** [comment]
Hm I'm having trouble picturing how that would work, but I imagine it would be a way to share pieces of logic between the binding sets of two different resources. That does sound useful, but it isn't really what I'm looking for in this case.

I'm looking for a way to apply the exact same set of bindings to two different scope names in my view that actually represent different instances of the same resource. So using my example from above, both the `:nav_user` and `:user` scopes represent Users, and therefore I want both of them to contain every user-applicable binding.

Another potential way to accomplish what I want would be the ability to pass a second argument to the view's `scope` method. So doing something like `view.scope(:user_nav, :user).apply(some_user)` would tell presenter to find the `:nav_user` scope and apply the `some_user` object to it as if it was a `:user` scope instead of a `:nav_user` scope.

I think I'd still prefer the multiple scopes method from above since it only requires a single addition to the binding set definition instead of per-use overrides in each route definition, but either would work I think.

P.S. I might have completely missed the point of your proposed binding mixins, so please enlighten me if I did :smile:

**Comment by bryanp** [comment]
The issue I have with the suggestion is that I think it would be rare that *all* of the *exact* same set of bindings were needed for two different scopes. And if it's just aliased names, there's no way to make exceptions. With the shared binding approach, you could abstract out the common bindings and include them in all of the scopes that were necessary.

**Comment by rjclardy** [comment]
Yeah I think we just view the problem differently. I think either option would work, but I actually see each one as better suited for a different scenario...

For a single resource, I only want to manage a single binding set. The ability to add aliases would make it easy for every scope that represents a User object to have access to all of the User bindings. That seems like a win to me, and it means I don't have to think about which User scope has access to which User bindings and then refactor them whenever my needs change.

I see the shared binding approach as something that would be useful for sharing bindings across *different* resources. Though I can't think of very many times that I've wanted to do that. And while shared bindings would probably work for my single-resource example above, it's not the way I'd personally prefer to manage them.

**Comment by bryanp** [comment]
My vote is to implement shared bindings and hold off on multiple scopes for now. The reason for this is shared bindings seems consistent and something that could be useful every now and then. I can see where multiple scopes would also be handy, but I am concerned about the implementation.

This concern is mainly because I think there may actually be a larger issue here that can be solved in a different way. When it comes down to it, the real issue is that there are two parts of the view that represent the same underlying data, we just want to address them separately. A `scope` is used to define a data type for a view, and it also happens to be how we address it. Perhaps there's some other way to distinguish or name nodes of the same scope with a more context-specific name.

Hopefully that makes sense?

**Comment by rjclardy** [comment]
Yeah that makes sense, I'm sure there are other options out there. We could add a new attribute called `data-alias` that lets the backend refer to it by its alias instead of its scope, while bindings would still use the scope.

Something like that would have the same effect that I'm looking for without messing with the semantic definition of a `scope`, so I'd be happy with that. I just don't want to have to manage multiple binding sets for a single data type solely to distinguish between front-end contexts.

**Comment by bryanp** [comment]
Good options here; we'll nail down for sure when we get to implementation.
