### ISSUE TITLE
Make it possible to setup delete buttons.

### ISSUE THREAD

**Issue by bryanp** [pakyow/pakyow#97]
You're currently on your own when creating links that hit a delete route. I'd like to make this easier. This issue is somewhat related to #96 as the result should be a form that submits to the delete route:

``` html
<form action="/foo/1" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="submit" value="Delete">
</form>
```

**Comment by jphager2** [comment]
So should it be inferred from the route? I'm having a hard time imagining how this would work. Since I imagine that the form will have to be picked up by javascript to create the DELETE request, would an approach like the one used in rails (setting the `data-method` attribute to `delete` on a link, for example) also work?

**Comment by bryanp** [comment]
Yes, the way you explain it is roughly what I was thinking. Hoping this can leverage some of the component stuff I'm working on, where backend logic is invoked automatically on a view component. In practice, you would add a `data-ui="deletable"` to the UI element acting as a delete button, and Pakyow would take care of wrapping it in the form during initial render. There would also be a JavaScript side to the component that would perform the delete action over a WebSocket rather than submitting the form (with form submission being the fallback if things weren't working right). So, this would give you, the developer, power to define your UI, without worrying about the implementation details of the form.
